export const PUBLIC_KEY = `-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCql79cIOM9HsP8JtTxHgQZkbsz
9DZbraHYa4aF8kzL/AGLRMY4mj6F7Kjr4EpXSIvuavHvk+nJLOdbNQI+oKRL7s9l
b0pB59Hc/WLDHMNWODT+eA8Rarth8yJaRljXSVdfgP3Hj3MTimZDV84QJKzuFjeF
c2OtkS0EJ7pjyauZHwIDAQAB
-----END PUBLIC KEY-----`